CLASS zpru_cl_m_itm_feature_control DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zpru_cl_m_itm_feature_control IMPLEMENTATION.
ENDCLASS.
