CLASS zpru_cl_m_itm_authorization DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zpru_cl_m_itm_authorization IMPLEMENTATION.
ENDCLASS.
